### PR TITLE
refactoring using google styleguide, migrating to gradle, etc...

### PR DESCRIPTION
**Pull request by D33VIL**
Learning by doing
First I wanted to say that this is my first pull request and I'm sorry if its not the best, I'll definitely work on that ^^ and by the way I apologize for the commit messages which do not contain much information. Therefore the summary of my commits:

Summary
I actually did not touch much of the code logic, I mostly worked on refactoring the code. Means I ...

... set a maximum line length of 110
... refactored local variable names due to conventions
... changed class names
... changed a few code comments (but did not write javadoc stuff cause too lazy)

and generally revised the code using the google style guide, pmd, and spotbugs (as you can see in the config directory).

The most significant change I made was the migration from Maven to Gradle and therefore optimizing the build script. Furthermore I optimized helper class methods to remove redundant instances, added asynchronous task evaluation with completable futures, added Lombok annotations, improved testing dependencies and finally answered the question wether the reference of neuralNetwork changes by wrapping it with an AtomicReference.

**Latest commit**
As you may have recognized the new pull request contains just one more commit where some format editing has been made.

### CODE REVIEW

**Comment by Nova41** [comment]
That's a huge change... I'd say you can create your own fork.

**Comment by Nova41** [comment]
I'm sorry that I don't have time to audit thoroughly. I appreciate the effort, but I doubt those changes are necessary and will improve performance.

I only use maven and so moving to gradle may cause unnecessary troubles. Same goes for naming,  training network asynchronously with java concurrency api, and using lomlok. Thanks for the help about optimizing the helper class! It would be the best if you can create an independent pull request about it.

**Comment by D33VIL** [comment]
Thank you for looking into my pull request and giving some feedback :) . I will definitely work on my commit messages as well as the amount of changes per pull request and I guess you are right about the low need of most changes, but I´m glad that I could improve the helper class. Therefore I will close this request and create an independant one containing this change. Last words - if you find the time, you should look into gradle ^^, apart from that cya and good luck with your stuff 👍 !

**Comment by Nova41** [comment]
No problem! Thanks for contributing to the project! Have a good one 👍

**Pull request closed without merging**
